server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  cloud:
    gateway:
      routes:
        - id: LANCAMENTO-SERVICE
          uri: lb://LANCAMENTO-SERVICE
          predicates:
            - Path=/lancamento/**
          filters:
            - name: CircuitBreaker
              args:
                name: LANCAMENTO-SERVICE
                fallbackuri: forward:/microserviceFallBack
        - id: FLUXODECAIXA-SERVICE
          uri: lb://FLUXODECAIXA-SERVICE
          predicates:
            - Path=/fluxodecaixa/**
          filters:
            - name: CircuitBreaker
              args:
                name: FLUXODECAIXA-SERVICE
                fallbackuri: forward:/fluxodecaicaserviceFallBack
